### ISSUE TITLE
codecov doesn't respect ignore

### ISSUE THREAD

**Issue by williamFalcon** [williamFalcon/pytorch-lightning#65]
need to add some ignore files to codecov... but it seems to not care about the ignore part:

```
coverage:
  precision: 0  # 2 = xx.xx%, 0 = xx%
  round: nearest # how coverage is rounded: down/up/nearest
  range: 40...100 # custom range of coverage colors from red -> yellow -> green
  status:
    # https://codecov.readme.io/v1.0/docs/commit-status
    project:
      default:
        against: auto
        target: 99% # specify the target coverage for each commit status
        threshold: 20% # allow this little decrease on project
        # https://github.com/codecov/support/wiki/Filtering-Branches
        # branches: master
        if_ci_failed: error
    # https://github.com/codecov/support/wiki/Patch-Status
    patch:
      default:
        against: auto
        target: 40% # specify the target "X%" coverage to hit
        # threshold: 50% # allow this much decrease on patch
    changes: false
    ignore:
      - "pytorch_lightning/utilities/arg_parse.py"
      - "raise *"
```

@Borda
